### ISSUE TITLE
NTR: heterologous species

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/phi-eco#10]
Also edit 
PECO:0005029 tobacco host assay ->
heterologous species tobacco
4477353

After today's meeting with @ValWood we decided to move 'heterologous species' out of 'evidence' and into 'conditions'. Discussed in relation to https://github.com/PHI-base/curation/issues/19
There may be some commonly used species eg 'tobacco' that require their own term eg PECO:0005029

Below to add to another ticket -maybe on config tracker??

The evidence code 'Macroscopic observation in heterologous species' -> 'Macroscopic observation'
 
The following text or similar would be useful to add to the conditions selection page
'Please add experimental conditions, conditions are aspects of the experimental setup independent of the genotype of the species under study ie pathogen/host strain or construct. They include any third party species used as a experimental assay system (heterologous species).

**Comment by CuzickA** [comment]
Maybe 'heterologous host species' would be clearer and avoid confusion with 'heterologous organism delivery system'.

**Comment by ValWood** [comment]
I would just like to add a note. This isn't the same as a complementation experiment, and the  3rd party genotype is not relevant (directly ) to the experiment. This is for the situation where a pathogen protein and a host protein  (that are known to interact) are both inoculated into a different species where the outcome of their presence is known to be the same as in the host environment. So, these experiments are only assessing the outcome of the specific interactions  (usually a pathogen effector and a  host receptor). The 3rd party is only acting as an assay/petri dish, it seems closer to the experimental set up than anything else.
We could shoehorn into evidence but this would make it difficult to align with the actual evidence. We would need to allow > evidence.

**Comment by jseager7** [comment]
> The evidence code 'Macroscopic observation in heterologous species' -> 'Macroscopic observation'

@CuzickA pathogen-host interaction phenotypes already have the following evidence codes:
      
- Macroscopic observation (qualitative observation)
- Macroscopic observation (quantitative observation)

Do you want to just remove 'Macroscopic observation in heterologous species' in this case, or do you want an evidence code that doesn't distinguish between qualitative and quantitative observation?

**Comment by jseager7** [comment]
> The following text or similar would be useful to add to the conditions selection page

This text currently isn't configurable, so we'll have to add new configuration to Canto to support this. I'll open an issue on the Canto tracker.

**Comment by CuzickA** [comment]
> Do you want to just remove 'Macroscopic observation in heterologous species' 

Yes please
