### ISSUE TITLE
NTR + arborcandin C

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/phi-eco#29]
For https://github.com/PHI-base/curation/issues/145
Also see https://github.com/PHI-base/phipo/issues/397

**Comment by jseager7** [comment]
@CuzickA should this term name be capitalised? Other sources aren't consistent about capitalising 'arborcandin': some use 'Arborcandin' and others 'arborcandin'. Other terms in PHI-ECO that are similar to this are not capitalised, e.g. cyclosporin A and antimycin A.

**Comment by CuzickA** [comment]
Good spot thanks. It should be 'arborcandin C'.

**Comment by jseager7** [comment]
Closed by commit 210f1e8.
