### ISSUE TITLE
NTR: + PTI inducer

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/phi-eco#8]
Needed for https://github.com/PHI-base/curation/issues/66

Use this as a grouping term as not possible to create a condition for every PTI-inducer used

![image](https://user-images.githubusercontent.com/11753634/82310181-f49bb280-99bb-11ea-884c-feb7f5958423.png)

Term label
+ PTI inducer

Parent
'chemical added or excluded'
'grouping excess'

Def:
An experimental condition in which a PAMP triggered immunity (PTI) inducer was added to the experiment. This PTI inducer could be in the form of a chemistry or a pathogenic or non-pathogenic organism.

**Comment by jseager7** [comment]
@CuzickA I've added this to the PHI-ECO spreadsheet. If you're happy with what's there and this doesn't need reviewing, I can add it to phi-eco.owl.

**Comment by jseager7** [comment]
Note that I've also put the term in the 'Grouping_terms' subset.

**Comment by CuzickA** [comment]
@jseager7 That's great, thanks James. Please go ahead and add it.

**Comment by CuzickA** [comment]
> 'Grouping_terms' subset.
what does this mean?

**Comment by jseager7** [comment]
> 'Grouping_terms' subset.
> what does this mean?

Some of the terms that were in PomBase's version of PECO have an 'in_subset' annotation property on them (oboInOwl:inSubset), which links to the annotation property for '[Grouping_terms](http://purl.obolibrary.org/obo/peco#Grouping_terms)', but I've now realised that this causes them to be excluded from the conditions lookup (similar to the 'qc_do_not_annotate' annotation properties), so I've removed the subset annotation.

**Comment by CuzickA** [comment]
Ok thanks
