### ISSUE TITLE
Obsolete 'host assay in leaf' PECO:0005030

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/phi-eco#9]
Val and I decided to capture this information using the AE BTO instead. 
https://github.com/PHI-base/curation/issues/19

**Comment by CuzickA** [comment]
This term has still not been obsoleted.

@jseager7 please could you see if this condition has been used in any curation sessions. Thanks.

**Comment by jseager7** [comment]
Based on an export from 18 January, this term has only been used in [PMID:16965554](https://canto.phi-base.org/curs/87e386b652573063), but it's been used pretty extensively there. Seems like there are a few other obsolete phenotype terms and experimental conditions in the session.

**Comment by CuzickA** [comment]
Thanks.

It looks like this sessions needs some work. 

Plan
i) remove the 'host assay in leaf' condition from this session NEXT
ii) reannotate session with metagenotype controls etc after I have finished reannotating the 10 sample papers required for the publication

**Comment by CuzickA** [comment]
I've now done
i) remove the 'host assay in leaf' condition from this session

@jseager7 shall I obsolete the term via Protege?

**Comment by jseager7** [comment]
@CuzickA Yes, I think obsoleting with Protege would be the best option.

To confirm it's worked, you should see this under the obsoleted term in the OBO file:
```
is_obsolete: true
```
Whereas in the OWL file, it should show something like this:
```
AnnotationAssertion(owl:deprecated obo:PECO_0005030 "true"^^xsd:boolean)
```

**Comment by CuzickA** [comment]
062dc88 term obsoleted
